# Generated by Django 2.2.10 on 2020-05-09 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('star_ratings', '0003_auto_20160721_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('konten', tinymce.models.HTMLField(default='Artikel Ini Belum Memiliki Konten')),
                ('thumbnail', models.ImageField(upload_to='img/artikelThumb')),
                ('tanggal_post', models.DateField()),
                ('link', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='martabak',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img/upload/%y/%m/%d')),
                ('price', models.IntegerField()),
                ('variant', models.CharField(choices=[('Manis', 'Manis'), ('Asin', 'Asin')], default='Manis', max_length=50)),
                ('size', models.CharField(choices=[('Besar', 'Besar'), ('Kecil', 'Kecil')], default='Besar', max_length=50)),
                ('deskripsi', models.TextField()),
                ('best_seller', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.STAR_RATINGS_RATING_MODEL)),
            ],
        ),
    ]
