# Generated by Django 2.2.10 on 2020-03-20 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.STAR_RATINGS_RATING_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='martabak',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img/upload/%y/%m/%d')),
                ('price', models.IntegerField()),
                ('variant', models.CharField(choices=[('Manis', 'Manis'), ('Asin', 'Asin')], default='Manis', max_length=50)),
                ('Size', models.CharField(choices=[('Besar', 'Besar'), ('Kecil', 'Kecil')], default='True', max_length=50)),
                ('deskripsi', models.TextField()),
                ('best_seller', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('rating', models.ForeignKey(default=models.CharField(max_length=50), editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.STAR_RATINGS_RATING_MODEL)),
            ],
        ),
    ]
