# Generated by Django 2.2.10 on 2020-03-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='martabak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img/upload/%y/%m/%d')),
                ('price', models.IntegerField()),
                ('variant', models.CharField(choices=[('Manis', 'Manis'), ('Asin', 'Asin')], default='Manis', max_length=50)),
                ('Size', models.CharField(choices=[('Besar', 'Besar'), ('Kecil', 'Kecil')], default='True', max_length=50)),
                ('deskripsi', models.TextField()),
                ('best_seller', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
