# Generated by Django 2.2.10 on 2020-03-21 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200321_0045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rating',
        ),
        migrations.AlterField(
            model_name='martabak',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='martabak',
            name='rating',
            field=models.ForeignKey(blank=True, default=models.CharField(max_length=50), editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.STAR_RATINGS_RATING_MODEL),
        ),
    ]
