# Generated by Django 2.2.10 on 2020-05-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200509_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martabak',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
