# Generated by Django 2.2.10 on 2020-03-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200311_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='martabak',
            name='rating',
        ),
    ]
