# Generated by Django 2.2.10 on 2020-03-21 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200321_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martabak',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.STAR_RATINGS_RATING_MODEL),
        ),
    ]
