# Generated by Django 2.2.10 on 2020-03-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_martabak_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('rating_object', models.IntegerField()),
            ],
        ),
    ]
