# Generated by Django 2.2.10 on 2020-05-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200509_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martabak',
            name='image',
            field=models.FileField(upload_to='img/martabak/%y/%m/%d'),
        ),
    ]
