# Generated by Django 2.2.10 on 2020-03-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200321_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='martabak',
            name='selected',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='True', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='martabak',
            name='Size',
            field=models.CharField(choices=[('Besar', 'Besar'), ('Kecil', 'Kecil')], default='Besar', max_length=50),
        ),
    ]
