# Generated by Django 2.2.10 on 2020-05-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200509_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='martabak',
            name='size',
        ),
        migrations.AddField(
            model_name='martabak',
            name='size_besar',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='martabak',
            name='size_kecil',
            field=models.BooleanField(default='False'),
        ),
    ]
