# Generated by Django 2.2.10 on 2020-03-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200321_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='martabak',
            name='selected',
        ),
    ]
