# Generated by Django 2.2.10 on 2020-05-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200509_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='martabak',
            name='price',
        ),
        migrations.AddField(
            model_name='martabak',
            name='highest_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='martabak',
            name='lowest_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
