# Generated by Django 2.2.10 on 2020-05-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200509_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martabak',
            name='size_besar',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='martabak',
            name='size_kecil',
            field=models.BooleanField(default='True'),
        ),
    ]
