# Generated by Django 2.2.10 on 2020-03-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200321_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='img/artikelThumb')),
                ('tanggal_post', models.DateField()),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
