# Generated by Django 2.2.10 on 2020-05-10 07:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20200509_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=65)),
                ('image', models.ImageField(upload_to='img/avatar')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('komentar', tinymce.models.HTMLField(default='Komentar Pelanggan')),
            ],
        ),
        migrations.AlterField(
            model_name='artikel',
            name='thumbnail',
            field=models.ImageField(upload_to='img/artikel'),
        ),
    ]
