# Generated by Django 2.2.10 on 2020-05-10 07:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20200510_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='konten',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='komentar',
            field=tinymce.models.HTMLField(),
        ),
    ]
