# Generated by Django 2.2.10 on 2020-05-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20200510_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='komentar',
            name='image',
            field=models.ImageField(upload_to='img/avatar/%y/%m/%d'),
        ),
    ]
