# Generated by Django 2.2.10 on 2020-05-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20200510_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='headline',
            field=models.BooleanField(default=True),
        ),
    ]
