# Generated by Django 2.2.10 on 2020-05-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_artikel_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='headline',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=50),
        ),
    ]
